
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";

const App = lazy(() => import("./pages/App.tsx"));
const Blog = lazy(() => import("./pages/Blog.tsx"));
const BlogPost = lazy(() => import("./pages/BlogPost.tsx"));
const DataImport = lazy(() => import("./pages/DataImport.tsx"));
const Documents = lazy(() => import("./pages/Documents.tsx"));
const ProductSearch = lazy(() => import("./pages/ProductSearch.tsx"));
const Services = lazy(() => import("./pages/Services.tsx"));

export const userRoutes: RouteObject[] = [
	{ path: "/", element: <App />},
	{ path: "/blog", element: <Blog />},
	{ path: "/blog-post", element: <BlogPost />},
	{ path: "/blogpost", element: <BlogPost />},
	{ path: "/data-import", element: <DataImport />},
	{ path: "/dataimport", element: <DataImport />},
	{ path: "/documents", element: <Documents />},
	{ path: "/product-search", element: <ProductSearch />},
	{ path: "/productsearch", element: <ProductSearch />},
	{ path: "/services", element: <Services />},
];
