// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";

const App = lazy(() => import("./pages/App.tsx"));
const Blog = lazy(() => import("./pages/Blog.tsx"));
const BlogPost = lazy(() => import("./pages/BlogPost.tsx"));
const Documents = lazy(() => import("./pages/Documents.tsx"));
const ProductSearch = lazy(() => import("./pages/ProductSearch.tsx"));
const Services = lazy(() => import("./pages/Services.tsx"));
const Wyroby = lazy(() => import("./pages/Wyroby.tsx"));
const WyrobDetail = lazy(() => import("./pages/WyrobDetail.tsx"));

// poLCA pages
const PolcaHome = lazy(() => import("./pages/PolcaHome.tsx"));
const PolcaCatalog = lazy(() => import("./pages/PolcaCatalog.tsx"));
const PolcaTechnology = lazy(() => import("./pages/PolcaTechnology.tsx"));
const PolcaStandards = lazy(() => import("./pages/PolcaStandards.tsx"));
const PolcaNews = lazy(() => import("./pages/PolcaNews.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App /> },
	{ path: "/blog", element: <Blog /> },
	{ path: "/blog-post", element: <BlogPost /> },
	{ path: "/blogpost", element: <BlogPost /> },
	{ path: "/documents", element: <Documents /> },
	{ path: "/product-search", element: <ProductSearch /> },
	{ path: "/productsearch", element: <ProductSearch /> },
	{ path: "/services", element: <Services /> },
	{ path: "/wyroby", element: <Wyroby /> },
	{ path: "/wyrob", element: <WyrobDetail /> },

	// poLCA routes
	{ path: "/polca", element: <PolcaHome /> },
	{ path: "/polca/catalog", element: <PolcaCatalog /> },
	{ path: "/polca/technology", element: <PolcaTechnology /> },
	{ path: "/polca/standards", element: <PolcaStandards /> },
	{ path: "/polca/news", element: <PolcaNews /> },

];